apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clickhouse-keeper.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clickhouse-keeper.labels" . | nindent 4 }}
data:
  keeper_config.xml: |
    <clickhouse>
        <logger>
            <level>warning</level>
            <console>true</console>
        </logger>
        <listen_host>::</listen_host>
        <keeper_server>
            <tcp_port>{{ .Values.service.clientPort }}</tcp_port>
            <server_id from_env="KEEPER_SERVER_ID"/>
            <log_storage_path>/var/lib/clickhouse/coordination/log</log_storage_path>
            <snapshot_storage_path>/var/lib/clickhouse/coordination/snapshots</snapshot_storage_path>
            <coordination_settings>
                <operation_timeout_ms>10000</operation_timeout_ms>
                <session_timeout_ms>30000</session_timeout_ms>
                <raft_logs_level>warning</raft_logs_level>
            </coordination_settings>
            <raft_configuration>
                {{- range $i := until (int $.Values.replicaCount) }}
                <server>
                    <id>{{ add $i 1 }}</id>
                    <hostname>{{ include "clickhouse-keeper.dnsName" $ }}-{{ $i }}.{{ include "clickhouse-keeper.dnsName" $ }}-headless.{{ $.Release.Namespace }}.svc.cluster.local</hostname>
                    <port>{{ $.Values.service.raftPort }}</port>
                </server>
                {{- end }}
            </raft_configuration>
        </keeper_server>
    </clickhouse>
